language: cpp
dist: bionic

os:
  - linux

compiler:
  - gcc
  - clang

env:
  - BUILD_CONFIGURATION=Release
  - BUILD_CONFIGURATION=Debug

install:
  - ./ci/install-${TRAVIS_OS_NAME}.sh

script:
  - ./ci/build.sh

notifications:
  email: false
